### PR TITLE
Fixes #8: fixing lint tests in louis-crawler

### LINKED ISSUE #8: Lint-test failed for louis-crawler
https://github.com/ai-cfia/louis-crawler/actions/runs/6340529474
unittest failed in this run

### PR DESCRIPTION
**Pull request by melanie-fressard**
issue #8

### CODE REVIEW

**Comment by melanie-fressard** [comment]
@k-allagbe pourrais tu checker les tests dans test_db.py ? ils donnent des erreurs que je ne pense pas pouvoir régler moi même...

exemple:
```======================================================================
ERROR: test_store_embedding_item (test_db.TestDBLayer.test_store_embedding_item)
sample test to check if store_embedding_item works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/ailab/db/crawler/__init__.py", line 151, in store_embedding_item
    cursor.execute(
  File "/home/vscode/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.ForeignKeyViolation: insert or update on table "ada_002" violates foreign key constraint "ada_002_token_uuid_fkey"
DETAIL:  Key (token_id)=(00000000-0000-0000-0000-000000000000) is not present in table "token".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/louis-crawler/tests/test_db.py", line 21, in test_store_embedding_item
    crawler.store_embedding_item(cursor, items.EmbeddingItem({
  File "/home/vscode/.local/lib/python3.11/site-packages/ailab/db/crawler/__init__.py", line 157, in store_embedding_item
    raise db.DBError(
ailab.db.DBError: Error storing embedding item for token 00000000-0000-0000-0000-000000000000

----------------------------------------------------------------------```

**Comment by melanie-fressard** [comment]
After investigation, turns out that ada_002 table has a constraint on token_id that should match a row in token table (thanks @k-allagbe for finding this !)

Therefore this test is not valid and the other ones I'm pretty sure they have similar problem so they should be either deleted or replaced with something else. 

What do you think @rngadam ?

**Comment by rngadam** [comment]
@melanie-fressard my request to you yesterday was to look into if these functions are separately tested in ailab-db, not so much to fix them because I'm already working on this in PR #4 

close this PR and check if there is test coverage for these functions in ailab-db.

**Comment by melanie-fressard** [comment]
> @melanie-fressard my request to you yesterday was to look into if these functions are separately tested in ailab-db, not so much to fix them because I'm already working on this in PR #4
> 
> close this PR and check if there is test coverage for these functions in ailab-db.

Just saw this, will do.
Corrected a few things (connection not closed, unused imports...)

**Comment by melanie-fressard** [comment]
For what I've seen, ailab-db test these functions :
link_pages, fetch_crawl, fetch_crawl_row, fetch-chunk_row, and fetch_chunk_id_without_embedding

the first 2 cover the same kind of tests as the file tests/test_goldie.py

Otherwise there is no coverage of louis-crawler in ailab-db

**Comment by rngadam** [comment]
> For what I've seen, ailab-db test these functions : link_pages, fetch_crawl, fetch_crawl_row, fetch-chunk_row, and fetch_chunk_id_without_embedding
> 
> the first 2 cover the same kind of tests as the file tests/test_goldie.py
> 
> Otherwise there is no coverage of louis-crawler in ailab-db

So we do need to test all functions within the ailab-db package as we also need to make sure these functions are maintained when we make breaking changes to the schema.

Commenting out tests is not a fix,  to help out here you can check you can develop your own test suite within ailab-db to preserve the function contract but update the implementation to work with the updated schema. Keeping in mind that we want to match the ailab-db Python versions functions with the schema.

**Comment by melanie-fressard** [comment]
> > For what I've seen, ailab-db test these functions : link_pages, fetch_crawl, fetch_crawl_row, fetch-chunk_row, and fetch_chunk_id_without_embedding
> > the first 2 cover the same kind of tests as the file tests/test_goldie.py
> > Otherwise there is no coverage of louis-crawler in ailab-db
> 
> So we do need to test all functions within the ailab-db package as we also need to make sure these functions are maintained when we make breaking changes to the schema.
> 
> Commenting out tests is not a fix, to help out here you can check you can develop your own test suite within ailab-db to preserve the function contract but update the implementation to work with the updated schema. Keeping in mind that we want to match the ailab-db Python versions functions with the schema.

So am I supposed to close this PR or do I still work on it to provide new tests instead of the one I commented out ?

Also, I will create a new PR on ailab-db to update tests regarding new schema, is it correct ?

**Comment by rngadam** [comment]
> So am I supposed to close this PR or do I still work on it to provide new tests instead of the one I commented out ?

Yes, close this one.
 
> Also, I will create a new PR on ailab-db to update tests regarding new schema, is it correct ?

Yes.

**Comment by melanie-fressard** [comment]
As discussed, will create a PR on ailab-db that will address test coverage for crawler functions.

**Pull request closed without merging**
